### ISSUE TITLE
Tooling: Allow Chaining of Custom Tooling Commands

### ISSUE THREAD

**Issue by AaronFeledy** [lando/core-next#31]

**Comment by AlexSkrypnyk** [comment]
@pirog 
Lando 4 is being in the works for several years, but we could really benefit from this feature in Lando 3.

The use case is quite significant: having a "build" or "full-build" command defined that would use other existing tooling commands so that devs could have a single command to get from "0 to 100".

In other non-lando projects, we are using Ahoy and Task that do allow these things.
Lando not  having this capability makes people have to use another wrapper (like that Ahoy or Task) around Lando which makes things more complicated than they should be.

Is it possible to develop this and bring it to v3 of Lando if this is a sponsored work? 

```
test-bdd:
    service: appserver
    description: Run BDD tests
    cmd: vendor/bin/behat

  test-unit:
    service: appserver
    description: Run unit tests
    cmd: vendor/bin/phpunit

  test:  <- something like this but without sub-process
    cmd: |
      lando test-unit
      lando test-bdd
```
