### ISSUE TITLE
Run Events as different users

### ISSUE THREAD

**Issue by generalredneck** [lando/core-next#47]
**Please explain your request and its importance in the form of a user story.**

As a developer, I would like to built events that can run as root so that I can alter files in the /etc/ folder.

**Please provide some detail on how lando can help solve this problem**

Some detail around this. I need to move an ecryption key to `/etc/encrypt/encrypt_key.key`. I can do this using Tooling but then it's up to me to document that you **MUST** run that command every time you start a fresh lando environment (eg: after destroy or on first build). I would  like to be able to use simular syntax in an event as we can in tooling, specifying the user.

**Is your feature request related to a problem? Please describe.**

The challenge I see is that Tooling actually supports a couple of different syntaxes that allow either commands on a single container, or multiple containers. One of which you can specify user and the other which you can't.
```
tooling:
  fire-everything:
    service: node
    description: Runs a seemingly random assortment of commands
    cmd:
      - source ~/.bashrc && npm install "$DEP_SET_BY_ENVVAR_SOURCED_BEFORE"
      - /helpers/my-custom-script.sh --max-power
      - ls -lsa
      - env | grep LANDO_
    user: root
```
versus
```
tooling:
  build:
    description: Manually invokes all our build steps
    cmd:
      - appserver: composer install
      - node: yarn install
      - node: yarn sass
```
I get that the second allows you to run commands against separate containers in order, but lacks options.

**Describe the solution you'd like**

 For the sake of simplicity, I would love to for events to support

```
events:
  post-start:
    service: appserver
    cmd: "whoami"
    user: root
```

**Describe alternatives you've considered**
Later it would be nice if we could do this in both tooling and events as I feel it is more verbose and provides an "interface object" for commands.

```
events:
  post-start:
    -
      service: appserver
      cmd: 
        -  "whoami"
        - "echo 'second command'
      user: root
    -
      service: database
      cmd: 
        -  "whoami"
        - "echo 'second command'
      user: root
     -
      service: appserver
      cmd: 
        -  "whoami"
        - "echo 'second command'
      user: root
tooling:
  build:
    -
      service: appserver
      cmd: 
        -  "whoami"
        - "echo 'second command'
      user: root
    -
      service: database
      cmd: 
        -  "whoami"
        - "echo 'second command'
      user: root
     -
      service: appserver
      cmd: 
        -  "whoami"
        - "echo 'second command'
      user: root
```
