### ISSUE TITLE
Possible regression: appserver_nginx scanner option causes error on latest v3.21.0-beta.15

### ISSUE THREAD

**Issue by vermario** [lando/core-next#70]
Hi! 

I updated this morning to the latest version available of lando plugins, and suddenly projects started failing with this message: 

```bash
$ lando info

ERROR ==> Cannot read properties of undefined (reading 'split')
```
By removing various parts of the setup I was able to narrow the problem down to this: 

```yaml
  appserver_nginx:
    scanner: false
```

Removing that part makes the project start again (although the scanner is not disabled for the nginx urls)

This is the whole `services` block: 

```yaml
services:
  appserver:
    overrides:
      volumes:
        - ./drupalfiles:/drupalfiles
  appserver_nginx:
    scanner: false
  database:
    type: mysql:8.0
    portforward: 49192
  memcached:
    type: memcached
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
```

This seems to me to be a regression, or is the appserver_nginx syntax not supported anymore?
