### ISSUE TITLE
How can the default path of lando ssh be changed?

### ISSUE THREAD

**Issue by ayalon** [lando/core-next#79]
I have a custom mount for my image. 
```
    type: node:18
    app_mount: false
    overrides:
      volumes:
        - "./frontend:/nuxt"
```

This works but when I do `lando ssh` I'm always at `/app` which is empty.
How can I tell lando to go to `/nuxt` when I login?
